### ISSUE TITLE
Cannot set my own colors into background visualizer

### ISSUE THREAD

**Issue by benchile55** [GuidoFe/visualizer#2]
Hello, there
I copied your script, run it in Manjaro Linux openbox distro and I cannot set my own colors. I have tried setting them into original cava config file  and followed your recommendations  but probably I am missing something or skipped a step. For urtvx terminal it works out fine but it's not doing the same as your line 138 states the change of color into one setting manually. Please help me  
https://i.imgur.com/BKUuB1L.png    comparison file
https://i.imgur.com/vKRy1ZL.png      your script of the visualizer
https://i.imgur.com/01w05BD.png    cava config  settings

**Comment by GuidoFe** [comment]
The foreground color in the cava file is green, so you have to set inCol to 2. You also have to uncomment the line in the cava file by removing the semicolon

**Comment by benchile55** [comment]
> The foreground color in the cava file is green, so you have to set inCol to 2. You also have to uncomment the line in the cava file by removing the semicolon

Grazie.. it solved my problems... Gracias miles
